"""Add index to royalty.portfolio_id

Revision ID: 280acc1e7e51
Revises: 9daf2bbe8648
Create Date: 2025-10-24 21:19:52.763576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '280acc1e7e51'
down_revision: Union[str, None] = '9daf2bbe8648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_royalty_portfolio_id'), 'royalty', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_royalty_portfolio_id'), table_name='royalty')
    # ### end Alembic commands ###
