"""Add portfolio link to royalty table

Revision ID: 9daf2bbe8648
Revises: 1ff92fda1e6d
Create Date: 2025-10-24 20:47:53.953426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9daf2bbe8648'
down_revision: Union[str, None] = '1ff92fda1e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('royalty', sa.Column('portfolio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'royalty', 'portfolio', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'royalty', type_='foreignkey')
    op.drop_column('royalty', 'portfolio_id')
    # ### end Alembic commands ###
